### ISSUE TITLE
Frontend (final) tidy up before release

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#107]
Final cleanup of components before releasing.

Checking / amending:

- [ ] print styling - use of `@mixins`
- [ ] link styling - use of `@mixins`
- [ ] add `12px` to spacing map and update key values to be the same as px size
- [x] alphabetise backstop.json component list
- [ ] triangle `@mixin` - care card and hero
- [ ] class names should use `heading` and not `header`
- [ ] check macros - each macro should use params and each component should have `classes` on surrounding element
- [x] check `.nhsuk-main-wrapper` spacing - should be `48px` on desktop and `40px` on mobile
- [x] body line-height
- [x] promo component colour variant - grey
- [ ] center align element helper class
- [x] update visual tests for all components
- [x] update change log
- [x] use the HTML syntax highlighting in READMEs

**Comment by AdamChrimes** [comment]
**Refactoring**

URL and HTML should be in uppercase in macros.
Use nhsuk-font mixin, not nhsuk-typography-responsive, @nhsuk-font mixin uses the latter.
Size SVG icons using modifier classes, not SCSS magic numbers.
Use 'background-colour', not just 'background' in SCSS.
Comments in SCSS should be with intent, not implementation.
Use spacing mixin, with numbers mapped and leave line comments.
Use the font size mixin, with numbers mapped and leave line comments.
Use the body line height function.
No magic numbers, variables only, if have to use magic numbers leave a line comment.
Write non blocking JavaScript, such as the Header on Line 198/238.
Use link style hover and focus states mixin.
Nested selector names should start with the selector, so not __element it would be .block__element.
If disabling sass-lint always leave a line comment as to why.
Use MQ for media queries, always mobile first and use $from.
Use print mixin for print colour and print hide
Use “heading” in macros rather than “title”
URLs in macros and html templates should link somewhere, default https://www.nhs.uk
 
**To do:**

Create list signage component, currently used on Homepage
List panel component, currently in Health A-Z
Back to top component, currently used in Health A-Z
Spacing 12px needs mapping, map the numbers in 10s so we can fit in numbers later on eg. 12 in between 10 and 20.
Add print mixin for border-top: 0;
Add print mixin for margin-top: 0;
Create print mixin for print colour and print hide
Change single quotes on macros to double quotes
Makes links black on print not blue.

**Comment by AdamChrimes** [comment]
Theres an issue when hovering over SVG icons, they disappear for a short period of time. Seen it happen on the Action link and also on the mobile drop down menu navigation items chevron.
