### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#171]
# Images

Use this issue to discuss the **Images** component.

[Preview the images component](https://nhsuk.github.io/nhsuk-frontend/components/images.html)

Find out more about the images component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

See our [contributing guidelines](https://github.com/nhsuk/nhsuk-frontend/tree/master/docs/contributing)

**Comment by mikemonteith** [comment]
> I wanted to ask about srcset, how might we make images responsive?

@karlgoldstraw I've created a separate issue here https://github.com/nhsuk/nhsuk-frontend/issues/422

**Comment by Demotive** [comment]
Out of interest, why is the width set at 2/3 for larger screens?

One could forsee use cases where this wasn't the case?

**Comment by bencullimore** [comment]
Hey @Demotive 

Here are some notes as to why images are set to 2/3 on large screens:

**Content team's needs**
Upon investigating our content teams needs for using images they suggested that the images should flow with the text content; not appear too prominent or separate (isolated). They also recommended that captions are as important as the images themselves, so must reflect this in their importance on the page.

**How to present images**
We found gallery views (images side by side) confusing to users - this also jarred with the content teams needs for the images to appear as part of the content. With gallery views, users either missed the images in the right-hand column or they didn't know how to interpret the sequence. To simplify this we recommend stacking images (if part of the content).

We also found users clicking images in gallery views - expecting them to appear larger in a pop-up modal. By increasing the size of the images, and having them stacked in one column (not in two) we didn't see anyone clicking on them to expand in testing.

**Hypothesis**
If the images are three quarters the reading space 
Then users will understand their place within the page (read as part of the text), and if multiple images are used, where the image sits in sequence
Because the images flow with the content

**Research findings**
Images tested well with all users, stating that they helped them understand how symptoms might appear and support written content
(usability lab, Leeds, 20th June 2018)

**Comment by Demotive** [comment]
@bencullimore that's really interesting thanks! We'll stick with the width recommended then :)

**Comment by bencullimore** [comment]
@Demotive I remember it was hard to define the 'success' in testing images. We were more concerned in ensuring they flowed with the content - for example, users didn't think that the page/section ended when an image started (which we'd heard about from 100% width images). 

But by all means - test in your context and let us know how you get on.

**Comment by Demotive** [comment]
It was more curiousity. Our context at the moment is using media (inc images) to assist in the answering of questions. Current roughs look more or less as you'd expect:

![burns](https://user-images.githubusercontent.com/1913757/60104675-d69ce200-9759-11e9-8c0f-ee65ebd9ddcc.png)

(this is pre users, so anything could happen)

**Comment by AdamChrimes** [comment]
Going to transfer this conversation to a new GitHub issue for better visibility. I think the comments in these placeholder issues get hidden abit.

**Comment by AdamChrimes** [comment]
Created a new issue @Demotive https://github.com/nhsuk/nhsuk-frontend/issues/492

**Comment by AdamChrimes** [comment]
Closing these individual placeholder issues. 

Please use the [NHS digital service manual backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues) to discuss the usage of this component. If you're having trouble with the code, or have found a bug, please [raise an issue on the NHS.UK frontend backlog](https://github.com/nhsuk/nhsuk-frontend/issues/new)
