### ISSUE TITLE
Promo

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#176]
# Promo

Use this issue to discuss the **Promo** component.

[Preview the promo component](https://nhsuk.github.io/nhsuk-frontend/components/promo.html)
[Preview the small promo component](https://nhsuk.github.io/nhsuk-frontend/components/promo-small.html)
[Preview the promo with no description component](https://nhsuk.github.io/nhsuk-frontend/components/promo-no-description.html)
[Preview the promo with image component](https://nhsuk.github.io/nhsuk-frontend/components/promo-with-image.html)

Find out more about the promo component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

See our [contributing guidelines](https://github.com/nhsuk/nhsuk-frontend/tree/master/docs/contributing)

**Comment by mcheung-nhs** [comment]
User testing with a visually impaired user brought up an interesting point regarding the promo component when in high contrast mode on a Windows machine. See screenshot below:
<img width="1435" alt="promo-high-contrast-before" src="https://user-images.githubusercontent.com/4749968/55493050-2e7eed80-5630-11e9-92d2-c281b4d1a7e9.png">
When hovering over a promo, the whole 'box' is the link. This caused very minor confusion because the cursor changes to a pointer, as expected, over the whole area, but the user thought they might be missing something because the cursor remained a pointer over lots of black space ie the area of the box where there is no text. In high contrast mode on Windows, you can't see that the promo is in a box, unlike in normal contrast mode.

It is possible to add a transparent border to the promo so that a border appears in high contrast mode on Windows, and obviously this doesn't show when in normal contrast mode (because it's transparent!). See image below:
<img width="1430" alt="promo-high-contast-after" src="https://user-images.githubusercontent.com/4749968/55493517-fb892980-5630-11e9-8702-730bcab52499.png">

**Comment by mcheung-nhs** [comment]
@AdamChrimes, @davidhunter08, @bencullimore - what do you think re transparent border?
https://github.com/nhsuk/nhsuk-frontend/pull/433

**Comment by AdamChrimes** [comment]
Closing these individual placeholder issues. 

Please use the [NHS digital service manual backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues) to discuss the usage of this component. If you're having trouble with the code, or have found a bug, please [raise an issue on the NHS.UK frontend backlog](https://github.com/nhsuk/nhsuk-frontend/issues/new)
