### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#179]
# Tables

Use this issue to discuss the **Tables** component.

[Preview the tables component](https://nhsuk.github.io/nhsuk-frontend/components/tables/index.html)

Find out more about the tables component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

See our [contributing guidelines](https://github.com/nhsuk/nhsuk-frontend/tree/master/docs/contributing)

**Comment by theturning** [comment]
I've been researching how we might show tables elegantly on mobile devices from an equally visually appealing and accessible point of view.

To achieve a responsive table layout I used `display:block;` on the td's and tr's. 
I also used the `data-label` attribute on each row to display the `thead` entries with each cell as a title. 

Unfortunately this means that iOS voiceover then treats the table td's as divs if you change their display mode and thus thinks the table doesn't exist. 

To get around this I've added the following ARIA roles:

- `role=”table"` to the table
- `role="row"` to the rows
- `role="columnheader"` to the th's
- `role="cell"` to the td's

These attribute additions help VO to recognise the table as a table once again whilst displaying responsively. 

Tested successfully with iOS VO, Mac VO, and NVDA.

Will make a pull request soon.

**Comment by beseven** [comment]
Hi all, related to tables and specifically around the caption in the table as a panel  https://nhsuk.github.io/nhsuk-frontend/components/tables/tables-panel.html - is the h3 necessary, or can the caption be used instead? similar to the https://design-system.service.gov.uk/components/table/. I believe that in this example screen readers would read out the info twice.

**Comment by lmortimer99** [comment]
Hi all, how are we planning to test this?

**Comment by beseven** [comment]
@lmortimer99 - is the question for me or @karlgoldstraw, or the team in general? Is the testing you are referring to user and/or automated accessibility? Thanks.

**Comment by karlgoldstraw** [comment]
Hi, I'm dropping my research notes here too. Please bear in mind that any work I've done has purely been 'in my lunchtime' and not tested with any humans.

My work: https://karlgoldstraw.github.io/cookieMonster/index-2.html

- Tested with VO, works
- Tested with NVDA, works
- **NOT TESTED WITH HUMANS YET**

### Desktop research

This is good because it shows what css `display` properties do to table semantics when applied. https://developer.paciellogroup.com/blog/2018/03/short-note-on-what-css-display-properties-do-to-table-semantics/ Basically VO then doesn’t ‘see’ the table as a semantic table anymore. We get around this by adding the ARIA roles to each row and cell.

This is good because it shows the _sort of_ code I used in action, with a little bit of js to help with the structure https://codepen.io/aardrian/pen/LQddwO

And that url, came from this article: http://adrianroselli.com/2018/02/tables-css-display-properties-and-aria.html

### Please note: my work hasn't been tested with humans, and older browsers.

**Comment by davidhunter08** [comment]
Hi @beseven

Regarding the panel heading, we didn't uncover any accessibility issues during user testing. As your context will be different, I'd recommended conducting your own usability testing including users with access needs.

Also, the h3 doesn't need to be the same as the caption. The heading was designed to be shorter, more succinct, to grab the users attention. We should probably update our example to reflect this.

**Comment by jiggott** [comment]
On the table panel component, is the `h3` optional or compulsory?

We are building this into the Wagtail CMS and we want to know whether or not to make the heading field compulsory.

**Comment by AdamChrimes** [comment]
@jiggott if you're wanting a Table with an optional `<h3>` you're best off using the regular [Table component](https://nhsuk.github.io/nhsuk-frontend/components/tables/index.html) which has a visually hidden caption.

If you want to use the [Table with a panel](https://nhsuk.github.io/nhsuk-frontend/components/tables/tables-panel.html) then yes the `<h3>` would be compulsory.

Using the Table panel was just a potential variant if people really wanted a different header to the caption.

**Comment by jiggott** [comment]
Thanks, Adam.

**Comment by markasrobinson** [comment]
Is it correct that the vertical alignment of text in tables is centre?

Would it be better if it was aligned top - so that it's easier to read if any of the columns get a bit long?

![image](https://user-images.githubusercontent.com/42185603/56351332-ca7a2e80-61c4-11e9-84a5-7c609c5fd7f3.png)

**Comment by davidhunter08** [comment]
Hi @markasrobinson, that is the correct alignment, but I agree that in this case, it would be better for the text to be aligned top.

However, I would argue that you shouldn't have that amount of information in a table cell and that you should try a different way of displaying that information. 

Is there a live example of this problem on NHS.uk?

**Comment by markasrobinson** [comment]
I can't show you where it's a problem on live, as live tables align top. 

I don't think there are any real examples of where it's quite that bad, anyway, and I agree we should avoid long tables whenever possible. But on mobile it's bound to be an issue, even with short tables.

e.g.

![image](https://user-images.githubusercontent.com/42185603/56355964-84769800-61cf-11e9-9925-6ee8347b9fe0.png)

As a general principle, it seems to me that it would be easier to read across the rows if the text all started at the same level, rather than moving your eyes up and down to find it?

**Comment by AdamChrimes** [comment]
Going to transfer this conversation to a new GitHub issue for better visibility. I think the comments in these placeholder issues get hidden from everyone a bit.

**Comment by AdamChrimes** [comment]
Closing these individual placeholder issues. 

Please use the [NHS digital service manual backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues) to discuss the usage of this component. If you're having trouble with the code, or have found a bug, please [raise an issue on the NHS.UK frontend backlog](https://github.com/nhsuk/nhsuk-frontend/issues/new)
