### ISSUE TITLE
Issue with NHS.UK survey banner when the screen is magnified

### ISSUE THREAD

**Issue by lmortimer99** [nhsuk/nhsuk-frontend#399]
Hi all,

Spotted this in the user research lab today. When the screen size is magnified 200x (and upwards), the survey banner takes up pretty much the entire screen. Fixed element at the bottom of the window - see screenshot.

![image 5](https://user-images.githubusercontent.com/46002162/53169739-ff5b7200-35d5-11e9-9dd0-c1124400dd56.png)

**Comment by mcheung-nhs** [comment]
Unfortunately, due to it's stickiness design, there probably isn't anything we can do about this when zoomed in. Maybe reduce padding in smaller viewports? If this is considered a real problem, then may have to look at it being redesigned. @davidhunter08 - thoughts?

**Comment by AdamChrimes** [comment]
We're going to revisit the design of feedback banner because we don't think it's very good in general. It was just a redesign of the legacy survey banner on the NHS website. There is also no guidance published in the NHS digital service manual about the usage of this component.

We've created an issue on the NHS digital service manual backlog to revisit it: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/114
