### ISSUE TITLE
Details: addDetailsPolyfill isn't designed to be called multiple times, causes issues for single page apps with multiple details components

### ISSUE THREAD

**Issue by andyfrost01** [nhsuk/nhsuk-frontend#450]
# Bug Report

## What is the issue?

We are using angularjs and therefore have a single page app and due to the started flag in the addDetailsPolyfill() we are unable to call this multiple times when another details element has been dynamically added to the DOM.

Ideally we would like the ability to;
* Call it again on the whole page
* Call it again on a particular root element, to scan a sub section of the page

## What steps are required to reproduce the issue?

To recreate the issue;
Run the addDetailsPolyfill function and then add another details element to the DOM and then try rerunning the addDetailsPolyfill, the if(NHSUK.details.started) will catch and return meaning that the new details element doesn't get the required new attributes in order to work.

## What was the environment where this issue occurred?

* Device: NA
* Operating System: Windows 10
* Browser: IE
* Browser version: Any
* NHS.UK frontend package version: 1.0
* Node version: 10.14.2
* npm version: 6.4.1

**Comment by AdamChrimes** [comment]
Hi @andyfrost01,

Unfortunately, the core frontend library team probably won't have time to look at this issue in the near future. Mainly due to resourcing on the NHS.UK programme, other frontend library backlog issues and that we don't currently have the expertise within the team for angularjs or JavaScript single page applications.

Hopefully someone from the community will pick it up. Have you attempted a fix? This could be something to contribute back to the system.

**Comment by AdamChrimes** [comment]
Hi @andyfrost01,

Did you have much luck at attempting to fix this issue?

**Comment by andyfrost01** [comment]
Not currently, as we are currently only using one instance of this component.

**Comment by AdamChrimes** [comment]
This might be potentially fixed by the work being done on https://github.com/nhsuk/nhsuk-frontend/issues/408 by @tomdoughty

**Comment by AdamChrimes** [comment]
This was released in [3.0.0](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md#300---7-november-2019)
