### ISSUE TITLE
Select Dropdown browser differences

### ISSUE THREAD

**Issue by tblacker7** [nhsuk/nhsuk-frontend#573]
# Bug Report

## What is the issue?

The select dropdown appears very differently in Firefox to Chrome:
<img width="909" alt="Screenshot 2019-12-06 at 10 36 28" src="https://user-images.githubusercontent.com/44897304/70316956-b434e780-1814-11ea-986e-c2506b4b410a.png">
(Chrome on left, Firefox on right)

## What steps are required to reproduce the issue?

Visit https://nhsuk.github.io/nhsuk-frontend/components/select/index.html in Chrome. Visit same page in Firefox

## What was the environment where this issue occurred?

MacBook Pro 13"
Mac OS Catalina
Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Firefox Quantum 69.0 (64-bit)

**Comment by AdamChrimes** [comment]
Hi @tblacker7 whilst there is a visual inconsistency, this is the because of the different browsers default styling for dropdowns. I'm not sure its possible to overwrite some of the default styling for selects (eg. the styling of the dropdown menu itself) without JavaScript.

It is the same with the GOV.UK Frontend.

**Comment by AdamChrimes** [comment]
Going to close this issue following the above comment.
