### ISSUE TITLE
Page jump on textarea focus & unfocus

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/nhsuk-frontend#600]
# Bug Report

## What is the issue?

Focusing and un-focusing on the textarea input causes the height to change, and all content underneath to jump up and down.

See: https://nhsuk.github.io/nhsuk-frontend/components/textarea/index.html

## What steps are required to reproduce the issue?

Go here: https://nhsuk.github.io/nhsuk-frontend/components/textarea/index.html or here https://service-manual.nhs.uk/design-system/components/textarea

Click on the textarea. Notice that the height changes.

## What was the environment where this issue occurred?

Include the following as a minimum e.g.
* Device: MacBook Pro
* Operating System: Catalina 10.15.3
* Browser: Google Chrome
* Browser version: 80.0.3987.149

**Comment by andrewbarnesweb** [comment]
Looks like it's because the border size is increased on focus. It's `2px` by default and `4px` when focused. One way to hack your way out of this is to change the padding to allow for the extra space that's taken up by the border

```css

.nhsuk-textarea {
  border: 2px solid #4c6272;
  padding: 6px;
}

.nhsuk-textarea:focus {
  border: 4px solid #212b32;
  padding: 4px;
}
```

The downside of this approach, is that the textarea's would have `2px` extra padding on by default. 

You could leave it `4px` and then drop to `2px` on focus, but that might be a bit close when the main time that users will be interacting and using the textarea will be when it's focussed.
