### ISSUE TITLE
font size of the Login page is small

### ISSUE THREAD

**Issue by kmlhsn** [nhsuk/nhsuk-frontend#624]
# Bug Report

## What is the issue?
font size of the Login page is small and login section design layout is not responsive
 https://www.nhs.uk/personalisation/login.aspx

## What steps are required to reproduce the issue?
1.go to https://www.nhs.uk/
2. scroll down to footer
3. click on "Profile editor login"

## What was the environment where this issue occurred?

 

* Device:Nexus 4, Lenovo Thinkpad T420
* Operating System: Android 5.1.1,  Windows 10. 
* Browser:Firefox 80, Chrome 84
* Browser version:
* NHS.UK frontend package version:
* Node version:
* npm version:

## Is there anything else you think would be useful in recreating the issue?

![image](https://user-images.githubusercontent.com/32615215/91667232-c41ff480-eb24-11ea-9661-d08fc930a19b.png)

**Comment by AdamChrimes** [comment]
Hey @kmlhsn thanks for raising this issue.

This looks likes its an issue with the website, rather than the frontend library. The website isn't using the frontend library and is still on the legacy design (which we had prior to the frontend library). This is something we're aware of the page is going through redevelopment, as we're currently looking at decommissioning some older services on the website. 

Going to close this issue as it doesn't relate the frontend library and is something we're looking at already.
