### ISSUE TITLE
Block navigation text from appearing in Google search snippet 

### ISSUE THREAD

**Issue by torchboxjen** [nhsuk/nhsuk-frontend#644]
Text about how to navigate the site (possibly accessibility text?), like "menu" and "search the NHS website" are able to be pulled through as snippets in search (in place of the meta description):

![image](https://user-images.githubusercontent.com/50023525/95090685-75fea200-071d-11eb-90a7-29510f5efb47.png)

Solution: Use the `data-nosnippet` tag to block this specific text from appearing in search results: https://developers.google.com/search/reference/robots_meta_tag#data-nosnippet-attr

@AdamChrimes & I have fixed the same issue with text from the cookie banner on NHS.UK appearing in search, by using the `data-nosnippet` tag.

**Comment by AdamChrimes** [comment]
Hi @torchboxjen thanks for raising this issue

I think the underlying issue here is the description meta on some of the NHS website pages. This specific example does have some description meta but it seems quite basic (`<meta name="description" content="Information about sharing health records.">`). 

I think it might be worth investigating more into why the meta data isn't being picked up by Google rather than trying to just to hotfix it with an uncommon HTML attribute (which only seems to be for Google). Whilst it would fix the problem, I think theres still the underlying issue of the page meta description not being picked up by Google. I think this might also help us create best practice when creating search optimised pages and page templates.

**Comment by AdamChrimes** [comment]
This isn't something we're going to go ahead with following the above comment. We would be adding extra code to the frontend library to hot-fix a specific browser.
