### ISSUE TITLE
Use of 2 font-size declarations in css

### ISSUE THREAD

**Issue by MarkMc1089** [nhsuk/nhsuk-frontend#879]
I am using the minified files for an R Shiny app. I found that lots of text appears much smaller than expected. This is due to there being 2 `font-size` declarations in many places, like this

```
@media (min-width: 40.0625em) {
    .nhsuk-list,ol,ul {
        font-size:19px;
        font-size: 1.1875rem;
        line-height: 1.47368
    }
}
```

The second declaration is the one that is used, resulting in much smaller pixel values than the first one. I can remove (or simply invalidate them as mentioned [here](https://github.com/moj-analytical-services/shinyGovstyle/issues/55)).

I understand that this is done to provide a fallback for browsers not supporting `rem` units. But it seems that the `rem` units and the pixel units are wildly different in size, so trying to understand how this works in practice, and just flagging up in case the `rem` units should actually be a little bigger!

**Comment by andymantell** [comment]
The rem font size units are dynamic, in that they are _relative_ to the font size on the html element (which defaults to 16px for the most part). In nhsuk-frontend the px value and the rem value there should end up being the same size, because nhsuk-frontend assumes a 16px base.

Have you got some other CSS in place on your app that is setting a base font size? If you're mixing nhsuk-frontend with other styles you will get issues.

**Comment by MarkMc1089** [comment]
Hi, thanks for the quick reply! Since it is Shiny, and pulls in a lot of CSS itself, I am not sure but am guessing that the default font-size must be set lower somewhere. I tried your suggestion and it works a treat:

```
/* NHS front-end toolkit assumes a default font-size of 16px  */
html {
    font-size: 16px!important
}
```
