### ISSUE TITLE
Action links rely on colour to convey meaning

### ISSUE THREAD

**Issue by hiten-livi** [nhsuk/nhsuk-frontend#925]
# Bug Report

## What is the issue?

An accessibility audit of our site has flagged the following non-compliance with WCAG Level A: 1.4.1 Use of Colour.
[Action links](https://service-manual.nhs.uk/design-system/components/action-link) rely on colour alone to convey meaning.

**WCAG Success Criterion**
[Success Criterion 1.4.1 Use of Colour (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color): Colour is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.

**WCAG Sufficient technique**
[G182](https://www.w3.org/WAI/WCAG21/Techniques/general/G182.html): Ensuring that additional visual cues are available when text colour differences are used to convey information.

## What steps are required to reproduce the issue?

Go to any site that uses action links, e.g.:
https://www.nhs.uk/

## What was the environment where this issue occurred?

Can be observed on all desktop devices including macOS Sonoma and Windows 11.

## Is there anything else you think would be useful in recreating the issue?

This is a core NHS design component; flagging this issue for your consideration

**Comment by anandamaryon1** [comment]
Hi @hiten-livi thank you for sharing your findings. 

The action link itself doesn't rely solely on colour, as it has the icon and it's large and bold text. This component has been through accessibility audits before and passed. 

We want to ensure we continually improve our designs based on feedback, so I've copied your comments onto the discussion for the action link component (https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/5). Since I've copied over your comment, I'll now close this ticket. 

We'll continue to monitor accessibility feedback on the action link component. If we find that other teams are reporting similar things, we'll revisit it.
